openapi: 3.0.0
info:
  version: '1.15'
  title: ph-namespace-store
  description: |
    Pääsuke public APIs:
    <ul>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/x-road-services-consumed-by-paasuke/">X-road services consumed by Pääsuke</a></li>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/paasuke-x-road-services-to-query-mandates/">X-road services to query mandates that are stored in Pääsuke (Oraakliliides)</a></li>
    </ul>
    
    Pääsuke UI APIs:
    <ul>
        <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-rolebinding-ui-api/">rolebinding-adapter-ui-api and document-adapter-ui-api</li>
        <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-mutator-ui-api/">mutator-adapter-ui-api, namespace-store-ui-api</li>
        <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-name-ui-api"/>name-adapter-ui-api</a></li>
    </ul>
    
    Pääsuke internal APIs:
    <ul>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-document-adapter-internal-api"/>document-adapter-internal-api, document-helper-internal, name-adapter-internal, sync-adapter-internal</a></li>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-namespace-store/">namespace-store-internal-api</li>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-rolebinding-store/">rolebinding-store and mutator-adapter-internal</li>
      <li><a href="https://app.swaggerhub.com/apis/aasaru/ph-document-store-internal-api/">document-store-internal-api</li>
    </ul>
    
    Types:
    <ul>
      <li><a href="https://app.swaggerhub.com/domains/aasaru/paasuke-common-ui-types/">Pääsuke common UI types</a></li>
      <li><a href="https://app.swaggerhub.com/domains/aasaru/paasuke-common-types/">Pääsuke common types used in internal and xRoad APIs</a></li>
    </ul>

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/aasaru/ph-namespace-store/1.15


tags:
  - name: namespace-store-internal

paths:

  /namespaces:
    get:
      tags:
        - namespace-store-internal
      summary: List namespaces with their roles for communication (for composing notifications and PDF files)
      operationId: getNamespaces
      parameters:
        - in: query
          name: ns
          description: Filter by namespace
          example: STAT_ESTAT
          required: false
          schema:
            type: array
            items:
             type: string
             example: 'BR_REPRIGHT'
            uniqueItems: true
        - in: query
          name: filterBySendNotifications
          description: If <b>true</b> then only returns namespaces that have sendNotifications=true. If this parameter is unspecified or set to <b>false</b> then no filtering is applied (results that are returned have both sendNotifications=false and sendNotifications=true).
          example: true
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: namespaces and their roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Namespace'


  /roles:
    get:
      tags:
        - namespace-store-internal
      summary: List roles with translations and with information whom this role can be assigned to and on what conditions the role can be assigned or deleted. 
      description: |
        When 'If-Modified-Since' is included in the request the service can respond with HTTP Status code 304 if nor roles have been changed since that time. If there have been changes to roles (the provider does not support this parameter) all results (that match the filters) are returned (even the ones that have modified time earlier than If-Modified-Since parameter)
      operationId: getRoles
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/If-Modified-Since'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/responses/RoleDefinitions'
        '304':
          description: List of roles is not modified. Might be returned only if request sent additional header "If-Modified-Since" and no changes have been done since that date.
        '403':
          description: Forbidden. Request not authorized.
        '503':
          description: Service is temporarily unavailable

components:
  schemas:
    Namespace:
      type: object
      properties:
        namespace:
          type: string
          description: Namespace code
          example: 'EESTI_EE'
        sendNotifications:
          type: boolean
          description: Should e-mail notification be sent to the representee and delegate if a role from this namespace is added or removed from a person.
        title:
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Translation'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
  
    Role:
      type: object
      properties:
        role:
          type: string
          example: STAT_ESTAT:Respondent
        title:
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Translation'
        description:
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Translation'
