openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/aasaru/x-road-services-consumed-by-paasuke/1.0.1

info:
  title: X-road services consumed by Pääsuke
  description: |
    <p>X-road service definitions that are standardized by Pääsuke but offered by other parties (like Tax and Customs Board) and consumed by Pääsuke.</p><p>To download the API descriptions from the right menu choose either Export -&gt; Download API -&gt; YAML Resolved (or JSON Resolved) or you can export a server stub in your favourite programming language.</p>More info can be found at <a href="https://github.com/e-gov/PH/">github.com/e-gov/PH</a>.
    <h2>Changelog since 1.0.0</h2>
    <h3>1.0.1</h3>
    <ul>
      <li>Added mandateTriplet.mandate.subDelegator</li>
      <li>Deprecated mandateTriplet.mandate.subDelegatorIdentifier in favour of mandateTriplet.mandate.subDelegator</li>
    </ul>
  version: 1.0.1
  license:
    name: Licensed under Apache 2.0 license
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /delegates/{delegate}/representees/mandates:
    get:
      summary: List persons the delegate can represent. Mandates (roles) are included in the response.
      operationId: getMandatesByDelegate
      description: |
        
      parameters:
        - name: delegate
          in: path
          description: <b>Identifier of the delegate (volituste saaja).</b> Can be one of the follwing&colon; <p>a)  'EE' followed by 8-digit legal entity code from Estonian Business Registry</p> <p>b) 'EE' followed by 11-digit national identity number</p> <p>c) Two-letter country code followed by eIDAS identification (1...254 symbols) - Pääsuke uses the value that was returned by Tara when the person logged into eesti.ee portal.</p>
          example: EE38302250123
          required: true
          schema:
            type: string
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/subDelegatedByForDelegateRepresenteesQuery'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-UserId'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Represented-Party'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
        - name: ns
          in: query
          description: Systems that only serve mandates from a single namespace can ignore this parameter.
          required: false
          example: ANNUAL_REPORTS
          schema:
            type: array
            items:
             type: string
             example: 'ANNUAL_REPORTS'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/responses/MandateTriplets'
        '400':
          description: bad input parameter
        '403':
          description: Forbidden. Request not authorized...

  /representees/{representee}/delegates/mandates:
    get:
      summary: List delegates who have any mandates that are currently valid or become valid in the future.
      operationId: getMandatesByRepresentee
      description: |

        
      parameters:
        - name: representee
          in: path
          description: <b>Identifier of the representee (volitaja).</b> Can be one of the follwing&colon; <p>a)  'EE' followed by 8-digit legal entity code from Estonian Business Registry</p> <p>b) 'EE' followed by 11-digit national identity number</p> <p>c) Two-letter country code followed by eIDAS identification (1...254 symbols) - Pääsuke uses the value that was returned by Tara when the person logged into eesti.ee portal.</p>
          example: EE10391131
          required: true
          schema:
            type: string
        - name: delegate
          in: query
          description: Only return mandates with this delegate (volitatu). This is used for TÖR queries. 
          required: false
          example: EE10391132
          schema:
            type: string
        - name: ns
          in: query
          description: Only return mandates with specified namespace. Systems that only serve mandates from a single namespace can ignore this parameter.
          required: false
          example: ANNUAL_REPORTS
          schema:
            type: array
            items:
             type: string
             example: 'BR_REPRIGHT'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/subDelegatedByForRepresenteeDelegatesQuery'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-UserId'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Represented-Party'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/responses/MandateTriplets'
        '400':
          description: Bad input parameter
        '403':
          description: Forbidden. Request not authorized.
        '422':
          description: Unprocessable request. Something went wrong.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Problem'

  /representees/{representee}/delegates/{delegate}/mandates:
    post:
      summary: Add a mandate to a delegate under a representee
      operationId: addMandate
      description: |
        <p>This query is for the following use-case. The end user (in our example EE39912310123) logs into Pääsuke (that runs under www.eesti.ee) and adds a mandate from there (for example the end user adds "GLOBAL1_EMTA:ACCOUNTANT" role (with the right to further sub-delegate it) for the company accountant Jüri Juurikas). After end user confirms adding of the mandate then Pääsuke makes this POST request for each mandate.</p> <p>NB! The end user can only add mandates that have assignableBy in the role definition and the end user must have one of the roles.</p>
      parameters:
        - name: representee
          in: path
          description: <b>Identifier of the representee (volitaja).</b> Can be one of the follwing&colon; <p>a)  'EE' followed by 8-digit legal entity code from Estonian Business Registry</p> <p>b) 'EE' followed by 11-digit national identity number</p> <p>c) Two-letter country code followed by eIDAS identification (1...254 symbols) - Pääsuke uses the value that was returned by Tara when the person logged into eesti.ee portal.</p>
          example: EE10391131
          required: true
          schema:
            type: string
        - name: delegate
          in: path
          description: <b>Identifier of the delegate (volituste saaja).</b> Can be one of the follwing&colon; <p>a)  'EE' followed by 8-digit legal entity code from Estonian Business Registry</p> <p>b) 'EE' followed by 11-digit national identity number</p> <p>c) Two-letter country code followed by eIDAS identification (1...254 symbols) - Pääsuke uses the value that was returned by Tara when the person logged into eesti.ee portal.</p>
          required: true
          example: EE38302250123
          schema:
            type: string
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-UserId'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Represented-Party'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/requestBodies/AddMandateTriplet'
      
      responses:
        '201':
          description: The request was fulfilled and the new mandate was created.
        '202':
          description: Accepted for processing but not immediately created.
        '400':
          description: Incorrect format of the payload
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Problem'
        '403':
          description: Forbidden. Request not authorized.
        '422':
          description: Unprocessable request. Something went wrong.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Problem'
        '501':
          description: This request is not supported.

  /representees/{representeeId}/delegates/{delegateId}/mandates/{mandateId}/subdelegates:
    post:
      summary: Sub-delegate a single mandate
      operationId: addSubDelegate
      description: |
        To add a sub-delegate for a specific mandate. The values of representeeId, delegateId and mandateId are taken from the output of the Mandate, from the 'addSubDelegate' link.

      parameters:
        - name: representeeId
          in: path
          description: Implementator can use any form of representee identifier (like internal person id). Pääsuke takes this value from 'addSubDelegate' link.
          example: 1236
          required: true
          schema:
            type: string
        - name: delegateId
          in: path
          description: Implementator can use any form of delegate identifier (like internal person id). Pääsuke takes this value from 'addSubDelegate' link.
          example: 4567
          required: true
          schema:
            type: string
        - name: mandateId
          in: path
          description: Implementator can use any form of mandate (or role) identifier (like internal mandate id). Pääsuke takes this value from 'addSubDelegate' link.
          required: true
          example: 8923032032
          schema:
            type: string
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-UserId'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Represented-Party'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/requestBodies/MandateToSubDelegate'
      
      responses:
        '200':
          description: Created
        '202':
          description: Accepted for processing but yet not added
        '403':
          description: Forbidden. Request not authorized.
        '404':
          description: Endpoint was not found.
        '422':
          description: Unprocessable request. Something went wrong. If mandate was not found then the system should retrun this response together with translation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Problem'
        '500':
          description: Reserved for errors returned by security server.
        '501':
          description: This operation is not supported.


  



  /representees/{representeeId}/delegates/{delegateId}/mandates/{mandateId}:
    put:
      summary: Edit mandate (by ending the validity of it)
      operationId: editMandate
      description: |
        To edit a mandate, currently the only supported actions are DELETE_WITHDRAW and DELETE_WAIVE which means ending the validity of the mandate. The values of representeeId, delegateId and mandateId are taken from the output of the Mandate, from the delete link.
      parameters:
        - name: representeeId
          in: path
          description: Implementator can use any form of representee identifier (like internal person id). Pääsuke takes this value from 'delete' link.
          example: 100548
          required: true
          schema:
            type: string
        - name: delegateId
          in: path
          description: Implementator can use any form of delegate identifier (like internal person id). Pääsuke takes this value from 'delete' link.
          required: true
          example: 754864
          schema:
            type: string
        - name: mandateId
          in: path
          description: Implementator can use any form of mandate (or role) identifier (like internal mandate id). Pääsuke takes this value from 'delete' link.
          required: true
          example: 8647
          schema:
            type: string
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-UserId'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Represented-Party'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      requestBody:
        $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/requestBodies/DeleteMandate'
      
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/responses/EditMandateResult'
        '400':
          description: Invalid parameter
        '403':
          description: Forbidden. Request not authorized.
        '404':
          description: Resource to delete was not found.
        '422':
          description: Unprocessable request. Something went wrong.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/schemas/Problem'
        '500':
          description: This error code is reserved for security server.
        '501':
          description: This operation is not supported.

  /roles:
    get:
      summary: List roles with translations and with information whom this role can be assigned to and on what conditions the role can be assigned or deleted. 
      description: |
        When 'If-Modified-Since' is included in the request the service can respond with HTTP Status code 304 if nor roles have been changed since that time. If there have been changes to roles (the provider does not support this parameter) all results (that match the filters) are returned (even the ones that have modified time earlier than If-Modified-Since parameter)
      operationId: getRoles
      parameters:
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/If-Modified-Since'
        - $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/parameters/X-Road-Id'
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/aasaru/paasuke-common-types/0.12#/components/responses/RoleDefinitions'
        '304':
          description: List of roles is not modified. Might be returned only if request sent additional header "If-Modified-Since" and no changes have been done since that date.
        '403':
          description: Forbidden. Request not authorized.
        '503':
          description: Service is temporarily unavailable
